#!/bin/bash

clean_file () {
	if [ -f $1 ]; then
		rm $1
	fi
}

verify_directory () {
	if [ -d $1 ]; then
		echo "$1"
	else
		mkdir $1
	fi
}

make clean
make
printf "\n\n\n____________________________________________________________________________\n\n\n"

verify_directory test

cp backbone test

cd test
echo "Test Folder :"
pwd
printf "\n"

if [ -f output.log ]; then
	rm output.log
fi

if ! command -v unzip &> /dev/null
then
	echo "Please install unzip comand. Pretty please..."
	exit
fi

if [ -n "$1" ]; then
  for z in "$@"
  do
    unzip ${z} > /dev/null
  done
else
  for z in *.zip
  do
    unzip ${z} > /dev/null
  done
fi

clean_file *.check
rm *.check

  for f in *.bbones
  do
      mv -- "$f" "${f%.bbones}.checkME"
  done


for f in *.routes
do
	./backbone ${f}
done

printf "\n\n\n____________________________________________________________________________\n\n" >> output.log
for f in *.bbones
do
  printf ${f}"\n" >> output.log
	  diff ${f} ${f%.bbones}.checkME >> output.log
	
  printf "\n\n\n____________________________________________________________________________\n\n" >> output.log
  
done

rm backbone

rm *.routes

for f in *.checkME
do
  mv -- "$f" "${f%.checkME}.bbones"
done
rm *.bbones
mv output.log ..
cd ..

printf "DONE! Thank you for Choosing Vidais Airlines today\n\n"
vim output.log

